services:
  - type: web
    name: junnediya-sms
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn sms_project.wsgi:application 
